---

# TODO? use {{ ansible_service_mgr }}
- name: 'reload netdata'
  systemd:
    name: 'netdata'
    state: 'restarted'

- name: 'reload smartd'
  systemd:
    name: 'smartd'
    state: 'restarted'

...
